CREATE TABLE "Usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "role" varchar(20) NOT NULL DEFAULT 'user',
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Rol" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "descripcion" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Permiso" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "descripcion" text
);

CREATE TABLE "UsuarioRol" (
  "usuario_id" int NOT NULL,
  "rol_id" int NOT NULL,
  "asignado_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("usuario_id", "rol_id")
);

CREATE TABLE "RolPermiso" (
  "rol_id" int NOT NULL,
  "permiso_id" int NOT NULL,
  PRIMARY KEY ("rol_id", "permiso_id")
);

CREATE TABLE "Caso" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "nombre_completo" varchar(200) NOT NULL,
  "fecha_nacimiento" date NOT NULL,
  "age" int,
  "gender" varchar(30),
  "altura" decimal(5,2),
  "peso" decimal(5,2),
  "skinColor" varchar(30),
  "hairColor" varchar(30),
  "eyeColor" varchar(30),
  "senas_particulares" text,
  "fecha_desaparicion" date NOT NULL,
  "disappearanceTime" time,
  "lugar_desaparicion" varchar(255) NOT NULL,
  "lastSeenLocation" varchar(255),
  "lastSeen" varchar(100),
  "circumstances" text,
  "clothing" text,
  "title" varchar(300),
  "description" text,
  "location" varchar(255),
  "priority" varchar(20) NOT NULL DEFAULT 'medium',
  "status" varchar(20) NOT NULL DEFAULT 'pendiente',
  "reporterName" varchar(200),
  "relationship" varchar(50),
  "contactPhone" varchar(20),
  "contactEmail" varchar(150),
  "additionalContact" varchar(200),
  "resolutionDate" date,
  "resolutionNote" text,
  "observaciones" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "FotoReferencia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "caso_id" int NOT NULL,
  "ruta_archivo" varchar(500) NOT NULL,
  "angulo" varchar(20) NOT NULL,
  "metadata" jsonb,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Embedding" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "foto_referencia_id" int UNIQUE NOT NULL,
  "vector" bytea NOT NULL,
  "dimension" int NOT NULL,
  "fecha_generacion" timestamp DEFAULT (now())
);

CREATE TABLE "Camara" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ip" varchar(45) UNIQUE NOT NULL,
  "ubicacion" varchar(255) NOT NULL,
  "activa" boolean NOT NULL DEFAULT true,
  "type" varchar(10),
  "resolution" varchar(20),
  "fps" int,
  "url" varchar(500),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Alerta" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "caso_id" int NOT NULL,
  "camara_id" int NOT NULL,
  "timestamp" timestamp NOT NULL DEFAULT (now()),
  "similitud" decimal(5,4) NOT NULL,
  "imagen" bytea,
  "estado" varchar(20) NOT NULL DEFAULT 'PENDIENTE',
  "prioridad" varchar(10) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Reporte" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date NOT NULL,
  "total_alertas" int DEFAULT 0,
  "casos_detectados" int DEFAULT 0,
  "coincidencias_confirmadas" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "AlertaReporte" (
  "alerta_id" int NOT NULL,
  "reporte_id" int NOT NULL,
  PRIMARY KEY ("alerta_id", "reporte_id")
);

CREATE TABLE "LogAuditoria" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "alerta_id" int,
  "type" varchar(20),
  "accion" varchar(100) NOT NULL,
  "detalles" text,
  "ip" varchar(45),
  "status" varchar(20),
  "timestamp" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "Notificacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(20) NOT NULL,
  "title" varchar(200) NOT NULL,
  "message" text NOT NULL,
  "severity" varchar(20) NOT NULL,
  "isRead" boolean DEFAULT false,
  "timestamp" timestamp NOT NULL DEFAULT (now()),
  "usuario_id" int,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "CasoActualizacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "caso_id" int NOT NULL,
  "date" date NOT NULL,
  "note" text NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "Usuario" ("email");

CREATE INDEX ON "Usuario" ("role");

CREATE INDEX ON "Usuario" ("status");

CREATE INDEX ON "Caso" ("usuario_id");

CREATE INDEX ON "Caso" ("status");

CREATE INDEX ON "Caso" ("priority");

CREATE INDEX ON "Caso" ("fecha_desaparicion");

CREATE INDEX ON "Caso" ("nombre_completo");

CREATE INDEX ON "FotoReferencia" ("caso_id");

CREATE INDEX ON "FotoReferencia" ("angulo");

CREATE INDEX ON "Embedding" ("foto_referencia_id");

CREATE INDEX ON "Camara" ("ip");

CREATE INDEX ON "Camara" ("activa");

CREATE INDEX ON "Camara" ("ubicacion");

CREATE INDEX ON "Camara" ("type");

CREATE INDEX ON "Alerta" ("caso_id");

CREATE INDEX ON "Alerta" ("camara_id");

CREATE INDEX ON "Alerta" ("timestamp");

CREATE INDEX ON "Alerta" ("estado");

CREATE INDEX ON "Alerta" ("prioridad");

CREATE INDEX ON "Reporte" ("usuario_id");

CREATE INDEX ON "Reporte" ("fecha_inicio");

CREATE INDEX ON "Reporte" ("fecha_fin");

CREATE INDEX ON "LogAuditoria" ("usuario_id");

CREATE INDEX ON "LogAuditoria" ("alerta_id");

CREATE INDEX ON "LogAuditoria" ("timestamp");

CREATE INDEX ON "LogAuditoria" ("accion");

CREATE INDEX ON "LogAuditoria" ("type");

CREATE INDEX ON "LogAuditoria" ("status");

CREATE INDEX ON "Notificacion" ("usuario_id");

CREATE INDEX ON "Notificacion" ("type");

CREATE INDEX ON "Notificacion" ("severity");

CREATE INDEX ON "Notificacion" ("isRead");

CREATE INDEX ON "Notificacion" ("timestamp");

CREATE INDEX ON "CasoActualizacion" ("caso_id");

CREATE INDEX ON "CasoActualizacion" ("date");

COMMENT ON TABLE "Usuario" IS 'Usuarios del sistema con acceso controlado por roles';

COMMENT ON TABLE "Rol" IS 'Roles que determinan permisos de acceso (Admin, Analista, etc.)';

COMMENT ON TABLE "Permiso" IS 'Permisos específicos del sistema (crear_caso, editar_alerta, etc.)';

COMMENT ON TABLE "UsuarioRol" IS 'Relación muchos a muchos entre Usuario y Rol';

COMMENT ON TABLE "RolPermiso" IS 'Relación muchos a muchos entre Rol y Permiso';

COMMENT ON TABLE "Caso" IS 'Casos de personas desaparecidas con información completa del frontend';

COMMENT ON TABLE "FotoReferencia" IS 'Fotos de referencia del rostro. Angulo: IZQUIERDO, FRONTAL, DERECHO';

COMMENT ON TABLE "Embedding" IS 'Representación matemática del rostro para reconocimiento facial (relación 1:1 con FotoReferencia)';

COMMENT ON TABLE "Camara" IS 'Cámaras del sistema de vigilancia (USB e IP)';

COMMENT ON TABLE "Alerta" IS 'Alertas generadas por coincidencias detectadas. Estado: PENDIENTE, REVISADA, FALSO_POSITIVO. Prioridad: ALTA, MEDIA, BAJA';

COMMENT ON TABLE "Reporte" IS 'Reportes estadísticos del sistema';

COMMENT ON TABLE "AlertaReporte" IS 'Relación muchos a muchos entre Alerta y Reporte';

COMMENT ON TABLE "LogAuditoria" IS 'Log de auditoría para trazabilidad de todas las acciones del sistema';

COMMENT ON TABLE "Notificacion" IS 'Sistema de notificaciones detectado en NotificationPanel.jsx';

COMMENT ON TABLE "CasoActualizacion" IS 'Historial de actualizaciones de casos detectado en CaseManagement.jsx:34-38,60-63,85-89,113-116';

ALTER TABLE "UsuarioRol" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id") ON DELETE CASCADE;

ALTER TABLE "UsuarioRol" ADD FOREIGN KEY ("rol_id") REFERENCES "Rol" ("id") ON DELETE CASCADE;

ALTER TABLE "RolPermiso" ADD FOREIGN KEY ("rol_id") REFERENCES "Rol" ("id") ON DELETE CASCADE;

ALTER TABLE "RolPermiso" ADD FOREIGN KEY ("permiso_id") REFERENCES "Permiso" ("id") ON DELETE CASCADE;

ALTER TABLE "Caso" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id") ON DELETE RESTRICT;

ALTER TABLE "FotoReferencia" ADD FOREIGN KEY ("caso_id") REFERENCES "Caso" ("id") ON DELETE CASCADE;

ALTER TABLE "FotoReferencia" ADD FOREIGN KEY ("id") REFERENCES "Embedding" ("foto_referencia_id") ON DELETE CASCADE;

ALTER TABLE "Alerta" ADD FOREIGN KEY ("caso_id") REFERENCES "Caso" ("id") ON DELETE CASCADE;

ALTER TABLE "Alerta" ADD FOREIGN KEY ("camara_id") REFERENCES "Camara" ("id") ON DELETE RESTRICT;

ALTER TABLE "Reporte" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id") ON DELETE RESTRICT;

ALTER TABLE "AlertaReporte" ADD FOREIGN KEY ("alerta_id") REFERENCES "Alerta" ("id") ON DELETE CASCADE;

ALTER TABLE "AlertaReporte" ADD FOREIGN KEY ("reporte_id") REFERENCES "Reporte" ("id") ON DELETE CASCADE;

ALTER TABLE "LogAuditoria" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id") ON DELETE RESTRICT;

ALTER TABLE "LogAuditoria" ADD FOREIGN KEY ("alerta_id") REFERENCES "Alerta" ("id") ON DELETE SET NULL;

ALTER TABLE "Notificacion" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id") ON DELETE CASCADE;

ALTER TABLE "CasoActualizacion" ADD FOREIGN KEY ("caso_id") REFERENCES "Caso" ("id") ON DELETE CASCADE;
